In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from sklearn.tree import DecisionTreeRegressor
from sklearn import tree

In [2]:
dataset =pd.read_csv('cleaned_dataset.csv')


In [10]:
dataset.head()

total_confirmed  total_deceased  total_recovered  total_tested  population
0          82044.0          3014.0          31493.0      569380.0  63864405.0
1          24206.0           559.0            517.0       16268.0   2862427.0
2          62051.0          2048.0            517.0       16268.0  43053054.0
3              0.0             0.0            517.0       16268.0     55312.0
4           5383.0            75.0            517.0       16268.0     77142.0

In [11]:
x= dataset.iloc[:, 1:-1].values
y= dataset.iloc[:, -1].values

In [12]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size =0.25, random_state =0)

In [13]:
print(x_train)

[[6.10000000e+01 5.17000000e+02 1.62680000e+04]
 [3.65200000e+03 2.48160000e+04 5.81637900e+06]
 [1.49330000e+04 3.81305000e+05 3.63383000e+06]
 [1.66500000e+03 5.17000000e+02 7.93277000e+05]
 [5.00000000e+00 5.17000000e+02 1.62680000e+04]
 [1.00000000e+01 5.17000000e+02 1.62680000e+04]
 [0.00000000e+00 5.17000000e+02 1.62680000e+04]
 [5.85000000e+02 5.17000000e+02 1.62680000e+04]
 [1.20500000e+03 9.82300000e+03 3.09092000e+05]
 [1.30000000e+01 5.17000000e+02 1.62680000e+04]
 [3.29000000e+02 5.17000000e+02 1.83342700e+06]
 [1.34100000e+03 2.61150000e+04 7.80864000e+05]
 [6.09690000e+04 1.31515000e+06 6.65921370e+07]
 [2.70000000e+01 5.17000000e+02 1.62680000e+04]
 [7.50000000e+01 5.17000000e+02 1.62680000e+04]
 [8.90000000e+02 5.17000000e+02 1.42115400e+06]
 [2.42500000e+03 1.70610000e+04 1.13694200e+06]
 [4.40000000e+01 5.17000000e+02 1.62680000e+04]
 [7.94000000e+02 5.17000000e+02 5.59016000e+05]
 [8.50000000e+01 5.17000000e+02 1.62680000e+04]
 [1.51000000e+03 5.17000000e+02 1.626800

In [ ]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(x_train, y_train)